apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - image: imlala/ubuntu-xfce-vnc-novnc:latest
        name: ubuntu
      env:
      - VNC_PASSWD=26418chz;
      - GEOMETRY=1280x768
      - DEPTH=24
volumes: 
  - /root/Downloads
  - /root/Desktop
environment:
  - VNC_PASSWD=26418chz;
  - GEOMETRY=1280x768
  - DEPTH=24
resources:
  memory: "3072Mi"
  cpu: "1000m"
volumes: 
  - /root/Downloads
  - /root/Desktop
  - /data
persistentVolume:
  enabled: true
  storageClass: standard
  size: 4.5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: ubuntu
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "ubuntu"
    port: 6080
  selector:
    app: ubuntu
